# Optimization Using Newton's Method

# Table of Contents

- [ 1 - Function in One Variable](#1)
- [ 2 - Function in Two Variables](#2)

## Packeges

In [2]:
import numpy as np

## Function in One variable

- Let's optimize function $f\left(x\right)=e^x - \log(x)$ (defined for $x>0$) using Newton's method.

In [3]:
def f_example_1(x):
    return np.exp(x) - np.log(x)

def dfdx_example_1(x): 
    return np.exp(x) - 1/x

def d2fd2x_example_1(x):
    return np.exp(x) + 1/(x**2)

In [4]:
print(f"f(2) = {f_example_1(2)}")
print(f"f'(2) = {dfdx_example_1(2)}")
print(f"f''(2) = {d2fd2x_example_1(2)}")

f(2) = 6.695908918370705
f'(2) = 6.88905609893065
f''(2) = 7.63905609893065


### Newton's Method

In [5]:
def newtons_method(x, dfdx, d2fd2x, num_iteration=100):
    for iteration in range(num_iteration):
        x = x - dfdx(x)/d2fd2x(x)
        print(x)
    return x

In [6]:
x_initial = 2
newtons_example = newtons_method(x_initial, dfdx_example_1, d2fd2x_example_1, num_iteration=25)
print(f"newtons method result : x_min = {newtons_example}")

1.098179669096158
0.5526822326177031
0.5669388602197535
0.5671432509315752
0.5671432904097824
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
0.5671432904097838
newtons method result : x_min = 0.5671432904097838


You can see that starting from the initial point $x_0 = 1.6$ Newton's method converges after $6$ iterations.

### let's compare this with with Gradient descent method

### Gradient descent Method

In [7]:
def gradient_descent(x, dfdx, num_iteration=100, learning_rate=0.1):
    for iteration in range(num_iteration):
        x = x - learning_rate * dfdx(x)
        print(x)
    return x

In [8]:
x_initial = 2
gradient_descent_example = gradient_descent(x_initial, dfdx_example_1, num_iteration=25, learning_rate=0.1)
print(f"Gradient Descent result : x_min = {gradient_descent_example}")

1.311094390106935
1.0163433560411375
0.8384280318695868
0.7264259949964103
0.6573185172692837
0.6164906465564866
0.5934575251990601
0.580937926487038
0.5743019179330655
0.5708373205048533
0.5690437508722686
0.5681194674349391
0.567644294086666
0.5674003115388165
0.5672751166518569
0.5672108965574768
0.567177959743891
0.5671610687814754
0.5671524069884393
0.567147965267642
0.5671456876039223
0.5671445196510079
0.5671439207435476
0.5671436136339261
0.5671434561534316
Gradient Descent result : x_min = 0.5671434561534316


in Gradient descent the convergence would appear after almost $20$ iterations

## Function in Two variable


Define the function $f(x, y)$ like in the videos, its gradient and Hessian:

\begin{align}
f\left(x, y\right) &= x^4 + 0.8 y^4 + 4x^2 + 2y^2 - xy - 0.2x^2y,\\
\nabla f\left(x, y\right) &= \begin{bmatrix}4x^3 + 8x - y - 0.4xy \\ 3.2y^3 + 4y - x - 0.2x^2\end{bmatrix}, \\
H\left(x, y\right) &= \begin{bmatrix}12x^2 + 8 - 0.4y && -1 - 0.4x \\ -1 - 0.4x && 9.6y^2 + 4\end{bmatrix}.
\end{align}

In [9]:
def f_example_2(x, y):
    return x**4 + 0.8*y**4 + 4*x**2 + 2*y**2 - x*y -0.2*x**2*y

def grad_f_example_2(x, y):
    return np.array([[4*x**3 + 8*x - y - 0.4*x*y],
                     [3.2*y**3 +4*y - x - 0.2*x**2]])

def hessian_f_example_2(x, y):
    hessian_f = np.array([[12*x**2 + 8 - 0.4*y, -1 - 0.4*x],
                         [-1 - 0.4*x, 9.6*y**2 + 4]])
    return hessian_f

### Newton's Method for Two variable

In [27]:
def newtons_method_2(f, grad_f, hessian_f,x_y, num_iteration=100):
    for iteration in range(num_iteration):
        x_y = x_y - np.matmul(np.linalg.inv(hessian_f(x_y[0,0], x_y[1,0])), grad_f(x_y[0,0], x_y[1,0]))
        print(x_y.T)
    return x_y

In [28]:
x_y_initial = np.array([[4], [4]])
newtons_example_2 = newtons_method_2(f_example_2, grad_f_example_2, hessian_f_example_2, x_y_initial, num_iteration=25)
print("Newton's method result: x_min, y_min =", newtons_example_2.T)

[[2.58273866 2.62128884]]
[[1.59225691 1.67481611]]
[[0.87058917 1.00182107]]
[[0.33519431 0.49397623]]
[[0.04123585 0.12545903]]
[[0.00019466 0.00301029]]
[[-2.48536390e-08  3.55365461e-08]]
[[ 4.15999751e-17 -2.04850948e-17]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
Newton's method result: x_min, y_min = [[0. 0.]]


In this example starting from the initial point $(4, 4)$ it will converge after about $9$ iterations. Try to compare it with the gradient descent now:

In [29]:
def gradient_descent_2(grad_f, x_y, learning_rate=0.1, num_iterations=100):
    for iteration in range(num_iterations):
        x_y = x_y - learning_rate * grad_f(x_y[0,0], x_y[1,0])
        print(x_y.T)
    return x_y

num_iterations_2 = 300; learning_rate_2 = 0.02; x_y_initial = np.array([[4], [4]])
# num_iterations_2 = 300; learning_rate_2 = 0.03; x_y_initial = np.array([[4], [4]])
gd_example_2 = gradient_descent_2(grad_f_example_2, x_y_initial, learning_rate_2, num_iterations_2)
print("Gradient descent result: x_min, y_min =", gd_example_2) 

[[-1.552 -0.272]]
[[-1.00667816 -0.27035727]]
[[-0.76722601 -0.26354393]]
[[-0.61199381 -0.2542789 ]]
[[-0.49957833 -0.24362609]]
[[-0.41356991 -0.23220381]]
[[-0.34561558 -0.22041345]]
[[-0.29081322 -0.20852957]]
[[-0.24600097 -0.19674484]]
[[-0.20899755 -0.1851958 ]]
[[-0.17822189 -0.17397885]]
[[-0.15248504 -0.1631609 ]]
[[-0.13086798 -0.15278673]]
[[-0.11264557 -0.14288438]]
[[-0.09723686 -0.13346909]]
[[-0.08417097 -0.12454632]]
[[-0.07306297 -0.11611405]]
[[-0.0635961  -0.10816464]]
[[-0.05550841 -0.10068622]]
[[-0.04858239 -0.09366384]]
[[-0.04263691 -0.08708035]]
[[-0.03752071 -0.08091713]]
[[-0.03310722 -0.07515463]]
[[-0.02929035 -0.06977285]]
[[-0.02598099 -0.06475166]]
[[-0.02310421 -0.06007107]]
[[-0.02059686 -0.05571146]]
[[-0.01840572 -0.05165372]]
[[-0.01648577 -0.04787936]]
[[-0.01479896 -0.04437062]]
[[-0.01331303 -0.04111048]]
[[-0.01200059 -0.03808275]]
[[-0.01083835 -0.03527203]]
[[-0.0098065  -0.03266375]]
[[-0.00888809 -0.03024417]]
[[-0.00806868 -0.02800031]]
[[

Obviously, gradient descent will converge much slower than Newton's method.